// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            7
// Async Callback (empty):               1
// Total number of exported functions:   9

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    qdr_contract
    (
        init => init
        calculatePromoRewards => calculate_promo_rewards
        getPurchasedAddresses => purchased_addresses
        getPurchasePosition => purchase_position
        getApy => apy
        getTotalPromoPurchased => total_promo_purchased
        purchase => purchase
        claimPromoRewards => claim_promo_rewards
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
