// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           12
// Async Callback (empty):               1
// Total number of exported functions:  15

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    qdr_contract
    (
        init => init
        upgrade => upgrade
        calculatePromoRewards => calculate_promo_rewards
        getPurchasedAddresses => purchased_addresses
        getPurchasePosition => purchase_position
        getApy => apy
        getTotalPromoPurchased => total_promo_purchased
        purchase => purchase
        claimPromoRewards => claim_promo_rewards
        setQdrMagAddress => set_qdr_mag_address
        setMaAddress => set_ma_address
        setTtAddress => set_tt_address
        setMbAddress => set_mb_address
        setPromoAddress => set_promo_address
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
